### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by kokujin** [feathers-plus/cli-generator-example#9]
I can start the example, js-nedb-services, but I cant run any graphql queries, see error below

```````
mw1 middleware is running
error:  NotAuthenticated: No auth token
    at new NotAuthenticated (/Users/kokujin/Development/Research/fplus_examples/cli-generator-example/js-nedb-services/node_modules/@feathersjs/errors/lib/index.js:93:17)
```````
How doe I authenticate a user that would be able to run the queries? Thanks

**Comment by eddyystop** [comment]
The Get Started docs ( https://generator.feathers-plus.com/get-started/#comprehensive-example ) refer to the repo. The repo's README mentions how to start the test scaffolding for the example ( https://github.com/feathers-plus/cli-generator-example#starting-the-client-test-harness ).

Basically `npm start` then point browser to //localhost:3030.

File `data/users.db` already has some users. Their passwords are the same as their first names.

**Comment by eddyystop** [comment]
I think I can close this as there's been no response. So I assume the response was adequete.
